Repository kluster-ai/docs, pull requests merged in 2025-07, with the labels that each got.

#142 Update tables with tool support
  .snippets/text/get-started/rate-limit.md
  get-started/models.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#145 List Styling Update
  .snippets/text/get-started/fine-tuning-supported-models.md
  get-started/dedicated-deployments.md
  get-started/fine-tuning/api.md
  get-started/fine-tuning/overview.md
  get-started/get-api-key.md
  get-started/integrations/crewai.md
  get-started/integrations/eliza.md
  get-started/integrations/immersive-translate.md
  get-started/integrations/langchain.md
  get-started/integrations/litellm.md
  get-started/integrations/llama-ocr.md
  get-started/integrations/msty.md
  get-started/integrations/pydantic.md
  get-started/integrations/sillytavern.md
  get-started/integrations/typingmind.md
  get-started/mcp/overview.md
  get-started/openai-compatibility.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
  tutorials/klusterai-api/effective-prompt-engineering.ipynb
  tutorials/klusterai-api/finetuning-sent-analysis.ipynb
  tutorials/klusterai-api/image-analysis.ipynb
  tutorials/klusterai-api/integrating-tools.ipynb
  tutorials/klusterai-api/keyword-extraction-api.ipynb
  tutorials/klusterai-api/llm-as-a-judge.ipynb
  tutorials/klusterai-api/model-comparison.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
  tutorials/klusterai-api/uploads-api.ipynb
Labels: A2 - Maintenance Minor, B0 - Needs Review

#107 Fran/rag tutorial
  llms.txt
  tutorials/klusterai-api/.pages
  tutorials/klusterai-api/rag.ipynb
Labels: A0 - New Content, B1 - Ready to Merge

#137 Refer to Dedicated Deployments in Tutorials
  llms.txt
  tutorials/klusterai-api/effective-prompt-engineering.ipynb
  tutorials/klusterai-api/image-analysis.ipynb
  tutorials/klusterai-api/integrating-tools.ipynb
  tutorials/klusterai-api/keyword-extraction-api.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/reliability-check.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
  tutorials/klusterai-api/uploads-api.ipynb
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#153 Tutorial Link Fixes
  llms.txt
  tutorials/klusterai-api/reliability-check.ipynb
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
Labels: A3 - Quick Fixes, B0 - Needs Review

#147 add combat hallucinations tutorial
  llms.txt
  tutorials/klusterai-api/.pages
  tutorials/klusterai-api/combat-hallucinations.ipynb
Labels: A0 - New Content, B0 - Needs Review

#169 Change focus to Code
  .api-reference/.nav.yml
  .api-reference/reference.md
  .snippets/text/kluster-api-onboarding.md
  .tutorials/.nav.yml
  .tutorials/klusterai-api/.DS_Store
  .tutorials/klusterai-api/.nav.yml
  .tutorials/klusterai-api/combat-hallucinations.ipynb
  .tutorials/klusterai-api/reliability.ipynb
  images/verify/code/quick-start/configuration-settings.webp
  images/verify/code/quickstart/quickstart-1.webp
  images/verify/code/tools/tools-1.webp
  llms.txt
  verify/.nav.yml
  verify/code/.nav.yml
  verify/code/integrations.md
  verify/code/overview.md
  verify/code/quickstart.md
  verify/code/tools.md
  verify/get-api-key.md
  verify/mcp/.nav.yml
  verify/mcp/client-integrations.md
  verify/mcp/cloud/platform.md
  verify/mcp/get-started.md
  verify/mcp/overview.md
  verify/mcp/sdk-integrations/openai-agents.md
  verify/openai-compatibility.md
  verify/overview.md
  verify/reliability/.nav.yml
  verify/reliability/chat-completion.md
  verify/reliability/overview.md
  verify/reliability/verify-api.md
  verify/reliability/workflow-integrations.md
Labels: A1 - Maintenance Major
