Repository kluster-ai/docs, pull requests merged in 2025-03, with the labels that each got.

#73 Adds full code snippets to quickstart guides
  .github/workflows/check-url-changes.yml
  .snippets/code/get-started/integrations/start-building/batch/batch-jsonl-01.py
  .snippets/code/get-started/integrations/start-building/batch/batch-jsonl-02.txt
  .snippets/code/get-started/integrations/start-building/batch/batch-jsonl-03.py
  .snippets/code/get-started/integrations/start-building/batch/batch-jsonl-04.py
  .snippets/code/get-started/integrations/start-building/real-time/real-time-01.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-01.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-02.txt
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekR1.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekR1.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-405.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-405.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-8.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-8.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.3-70.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.3-70.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.py
  .snippets/code/get-started/start-building/real-time/real-time-01.py
  .snippets/code/get-started/start-building/real-time/real-time-deepseekR1.md
  .snippets/code/get-started/start-building/real-time/real-time-deepseekR1.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-8.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-8.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-70.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-70.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-qwen2.5-7.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-qwen2.5-7.py
  .snippets/text/batch-models.md
  .snippets/text/real-time-models.md
  api-reference/reference.md
  get-started/openai-compatibility.md
  get-started/start-api.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  get-started/start-building/setup.md
  llms.txt
Labels: A1 - Maintenance Major

#75 Qwen image snippets and overall improvements
  .snippets/code/get-started/start-building/batch/batch-jsonl-01.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekR1.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-405.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-8.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.3-70.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.py
  .snippets/code/get-started/start-building/real-time/real-time-deepseekR1.md
  .snippets/code/get-started/start-building/real-time/real-time-deepseekR1.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-8.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-8.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-70.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.3-70.py
  .snippets/code/get-started/start-building/real-time/real-time-qwen2.5-7.md
  .snippets/code/get-started/start-building/real-time/real-time-qwen2.5-7.py
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
Labels: A2 - Maintenance Minor

#77 Update API Limitations
  .snippets/text/get-started/start-api/rate-limit.md
  api-reference/reference.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
  variables.yml
Labels: A2 - Maintenance Minor, B0 - Needs Review

#78 Fix missing bearer tags
  api-reference/reference.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#80 Adds Gemma 3 and DeepSeek V3 0324
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekV3-0324.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekV3-0324.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-gemma3-27.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-gemma3-27.py
  .snippets/code/get-started/start-building/real-time/real-time-deepseekV3-0324.md
  .snippets/code/get-started/start-building/real-time/real-time-deepseekV3-0324.py
  .snippets/code/get-started/start-building/real-time/real-time-gemma3-27.md
  .snippets/code/get-started/start-building/real-time/real-time-gemma3-27.py
  .snippets/text/batch-models.md
  .snippets/text/real-time-models.md
  api-reference/reference.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
Labels: A0 - New Content, B0 - Needs Review

#79 First tutorial feedback
  llms.txt
  tutorials/klusterai-api/.pages
  tutorials/klusterai-api/keyword-extraction-api.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification-api.ipynb
  tutorials/klusterai-api/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/.pages
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
Labels: A1 - Maintenance Major

#81 Update Colabs URLs
  llms.txt
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
Labels: A3 - Quick Fixes, B0 - Needs Review
