Repository kluster-ai/docs, pull requests merged in 2025-04, with the labels that each got.

#83 Add Async Requests to API Reference
  api-reference/reference.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#84 Adds image analysis notebook
  .snippets/code/get-started/start-building/batch/batch-jsonl-01.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-02.txt
  .snippets/code/get-started/start-building/batch/batch-jsonl-gemma3-27.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-gemma3-27.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-qwen2.5-7.py
  .snippets/code/get-started/start-building/real-time/real-time-gemma3-27.md
  .snippets/code/get-started/start-building/real-time/real-time-gemma3-27.py
  .snippets/code/get-started/start-building/real-time/real-time-qwen2.5-7.md
  .snippets/code/get-started/start-building/real-time/real-time-qwen2.5-7.py
  images/get-started/start-building/cat-image.jpg
  images/get-started/start-building/emoji-image.jpg
  images/get-started/start-building/parking-image.jpg
  llms.txt
  tutorials/klusterai-api/image-analysis.ipynb
  tutorials/klusterai-api/keyword-extraction-api.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
Labels: A0 - New Content, B0 - Needs Review, C2 - High

#85 Adds Llama 4 support
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama4-maverick.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama4-maverick.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama4-scout.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama4-scout.py
  .snippets/code/get-started/start-building/real-time/real-time-llama4-maverick.md
  .snippets/code/get-started/start-building/real-time/real-time-llama4-maverick.py
  .snippets/code/get-started/start-building/real-time/real-time-llama4-scout.md
  .snippets/code/get-started/start-building/real-time/real-time-llama4-scout.py
  .snippets/text/get-started/rate-limit.md
  api-reference/reference.md
  get-started/models.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
  tutorials/klusterai-api/.pages
  tutorials/klusterai-api/image-analysis.ipynb
Labels: A3 - Quick Fixes, B0 - Needs Review

#86 Update rate limits and incorporate some notebook feedback
  .snippets/text/get-started/rate-limit.md
  llms.txt
  tutorials/klusterai-api/image-analysis.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
Labels: A2 - Maintenance Minor, B0 - Needs Review

#87 Update rate limits
  .snippets/text/get-started/rate-limit.md
  llms.txt
  tutorials/klusterai-api/image-analysis.ipynb
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#90 Clarify Unsupported Params
  get-started/openai-compatibility.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#89 Add image Analysis Cookbook Link
  llms.txt
  tutorials/klusterai-api/image-analysis.ipynb
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#91 Image analysis improvements
  llms.txt
  tutorials/klusterai-api/image-analysis.ipynb
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#96 Add Embeddings to API Reference
  api-reference/reference.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#92 Correct API Spec Completion Windows
  api-reference/reference.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#95 Decom Llama 405 and DeepSeek v3
  .snippets/code/get-started/start-building/batch/batch-jsonl-01.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-02.txt
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekV3.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-deepseekV3.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-405.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-llama3.1-405.py
  .snippets/code/get-started/start-building/real-time/real-time-01.py
  .snippets/code/get-started/start-building/real-time/real-time-deepseekV3.md
  .snippets/code/get-started/start-building/real-time/real-time-deepseekV3.py
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.md
  .snippets/code/get-started/start-building/real-time/real-time-llama3.1-405.py
  .snippets/text/get-started/rate-limit.md
  api-reference/reference.md
  get-started/models.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
  tutorials/klusterai-api/finetuning-sent-analysis.ipynb
  tutorials/klusterai-api/keyword-extraction-api.ipynb
  tutorials/klusterai-api/llm-as-a-judge.ipynb
  tutorials/klusterai-api/model-comparison.ipynb
  tutorials/klusterai-api/multiple-tasks-batch-api.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
  tutorials/klusterai-api/text-classification/text-classification-curator.ipynb
  tutorials/klusterai-api/text-classification/text-classification-openai-api.ipynb
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#93 Add Uploads API to API Reference
  api-reference/reference.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#88 Add Prompt Engineering Notebook
  llms.txt
  tutorials/klusterai-api/.pages
  tutorials/klusterai-api/effective-prompt-engineering.ipynb
Labels: A0 - New Content, B0 - Needs Review
