Repository kluster-ai/docs, pull requests merged in 2025-06, with the labels that each got.

#113 Adding Fine-tuning to Get-Started section
  .snippets/code/get-started/fine-tuning/fine-tune.py
  .snippets/code/get-started/fine-tuning/prepare.json
  .snippets/text/get-started/fine-tuning-supported-models.md
  .snippets/text/kluster-api-onboarding.md
  get-started/.pages
  get-started/fine-tuning/.pages
  get-started/fine-tuning/api.md
  get-started/fine-tuning/overview.md
  get-started/fine-tuning/platform.md
  get-started/verify/.pages
  images/get-started/fine-tuning/fine-tuning-1.webp
  images/get-started/fine-tuning/fine-tuning-2.webp
  images/get-started/fine-tuning/fine-tuning-3.webp
  images/get-started/fine-tuning/fine-tuning-4.webp
  images/get-started/fine-tuning/fine-tuning-5.webp
  llms.txt
Labels: A0 - New Content, B0 - Needs Review, C1 - Medium

#126 Add Verify to API Reference
  api-reference/reference.md
  llms.txt
Labels: A1 - Maintenance Major, B0 - Needs Review

#130 New Mistral and Magistral Small Models
  .snippets/code/get-started/start-building/batch/batch-jsonl-magistral-small-2506.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-magistral-small-2506.py
  .snippets/code/get-started/start-building/batch/batch-jsonl-mistral-small-24b-instruct-2501.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-mistral-small-24b-instruct-2501.py
  .snippets/code/get-started/start-building/real-time/real-time-magistral-small-2506.md
  .snippets/code/get-started/start-building/real-time/real-time-magistral-small-2506.py
  .snippets/code/get-started/start-building/real-time/real-time-mistral-small-24b-instruct-2501.md
  .snippets/code/get-started/start-building/real-time/real-time-mistral-small-24b-instruct-2501.py
  .snippets/text/get-started/rate-limit.md
  get-started/models.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#133 fix 404
  get-started/verify/reliability/chat-completion.md
  get-started/verify/reliability/overview.md
  get-started/verify/reliability/workflow-integrations.md
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review

#135 Hide MCP Tools Content Page
  get-started/mcp/.pages
  get-started/mcp/cloud/api.md
  get-started/mcp/get-started.md
  get-started/mcp/integrations.md
  get-started/mcp/self-hosted.md
  get-started/mcp/tools.md
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review

#139 Adds PR Link Checker Workflow
  .github/workflows/check-url-changes.yml
  .github/workflows/pr-link-checker.yml
Labels: A1 - Maintenance Major
