Repository kluster-ai/docs, pull requests merged in 2025-05, with the labels that each got.

#99 Update Model Comparison
  llms.txt
  tutorials/klusterai-api/model-comparison.ipynb
Labels: A1 - Maintenance Major, B0 - Needs Review

#103 Add Llama OCR Integration page
  .snippets/code/get-started/integrations/llama-ocr/.DS_Store
  .snippets/code/get-started/integrations/llama-ocr/index.ts
  get-started/integrations/.pages
  get-started/integrations/llama-ocr.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#111 New Model: Mistral NeMo
  .snippets/code/get-started/start-building/batch/batch-jsonl-mistral-nemo-instruct-2407.md
  .snippets/code/get-started/start-building/batch/batch-jsonl-mistral-nemo-instruct-2407.py
  .snippets/code/get-started/start-building/real-time/real-time-mistral-nemo-instruct-2407.md
  .snippets/code/get-started/start-building/real-time/real-time-mistral-nemo-instruct-2407.py
  .snippets/text/get-started/rate-limit.md
  get-started/models.md
  get-started/start-building/batch.md
  get-started/start-building/real-time.md
  llms.txt
Labels: A2 - Maintenance Minor, B0 - Needs Review, C2 - High

#106 Albertov19/update llm judge
  llms.txt
  tutorials/klusterai-api/llm-as-a-judge.ipynb
  tutorials/klusterai-api/model-comparison.ipynb
Labels: A1 - Maintenance Major, B0 - Needs Review

#109 Update fine tuning tutorial
  llms.txt
  tutorials/klusterai-api/finetuning-sent-analysis.ipynb
  tutorials/klusterai-api/model-comparison.ipynb
  tutorials/klusterai-api/sentiment-analysis-api.ipynb
Labels: A1 - Maintenance Major, B0 - Needs Review
