Repository kluster-ai/docs, pull requests merged in 2025-08, with the labels that each got.

#171 too name has changed + recommended settings
  llms.txt
  verify/code/integrations.md
  verify/code/tools.md
Labels: A3 - Quick Fixes

#172 Code Tutorial: Cursor authentication with Nextjs
  images/verify/code/examples/cursor/example-cursor-1.webp
  images/verify/code/examples/cursor/example-cursor-2.webp
  images/verify/code/examples/cursor/example-cursor-3.webp
  images/verify/code/examples/cursor/example-cursor-4.webp
  images/verify/code/examples/cursor/example-cursor-5.webp
  llms.txt
  verify/code/.nav.yml
  verify/code/examples/.nav.yml
  verify/code/examples/cursor-firebase-nextjs.md
Labels: A0 - New Content, B0 - Needs Review, C2 - High

#181 patch output path for llms.txt
  scripts/llms_config.json
Labels: A3 - Quick Fixes, B0 - Needs Review

#184 fix urls
  verify/index.md
  verify/integrations/mcp.md
  verify/tools.md
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#186 Update VSCode Install Screenshots
  images/verify/code/integrations/vscode/vscode-integration-0.webp
  images/verify/code/integrations/vscode/vscode-integration-1.webp
  images/verify/code/integrations/vscode/vscode-integration-2.webp
  images/verify/code/integrations/vscode/vscode-integration-3.webp
  images/verify/code/integrations/vscode/vscode-integration-4.webp
  images/verify/code/integrations/vscode/vscode-integration-5.webp
  images/verify/code/integrations/vscode/vscode-integration-6.webp
  images/verify/code/integrations/vscode/vscode-integration-7.webp
  images/verify/code/integrations/vscode/vscode-integration-8.webp
  llms-full.txt
  verify/integrations/ide.md
Labels: A2 - Maintenance Minor, B0 - Needs Review
